Add Tamil translation
jenius-apps/ambie pull request #144
Opened 2021-03-06 08:44 UTC by Jaiganeshkumaran

Adds translation for Tamil (language code TA)

2021-03-20 22:32 UTC, dpaulino commented
There's been a few new strings. Do you mind updating?

2021-06-14 23:45 UTC, dpaulino commented
I think there's an issue with one of the strings

2021-06-17 11:09 UTC, Jaiganeshkumaran commented
@dpaulino I've fixed that issue. Can you merge this now?

2021-06-17 15:11 UTC, dpaulino commented
I think you're missing some new strings from the latest main branch. Can you pull from main?

2021-06-24 06:50 UTC, Jaiganeshkumaran commented
> I think you're missing some new strings from the latest main branch. Can you pull from main?
I have translated them now as well.

2021-06-27 19:42 UTC, dpaulino requested changes

2021-06-27 19:42 UTC, dpaulino commented on AmbientSounds.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "AmbientSounds.Tests", "AmbientSounds.Tests\AmbientSounds.Tests.csproj", "{190FE594-FDCE-4707-B01C-EE7C39C541F3}"
Can you revert this?

2021-06-27 19:42 UTC, dpaulino commented on AmbientSounds.sln
> +		{B0BA021E-FA43-4921-A25A-0004A43F7C40}.Debug|Any CPU.Deploy.0 = Debug|x86
Can you revert this?

2021-06-27 19:42 UTC, dpaulino commented on src/AmbientSounds.Uwp/AmbientSounds.Uwp.csproj
> +    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.19041.0</TargetPlatformVersion>
Revert as well please?

2021-06-27 19:43 UTC, dpaulino commented
@Jaiganeshkumaran Very sorry for the very long review times. This is my one last requested change. Once this is done, we'll merge ASAP. And if you can get the changes done within the next 16 hours, we can get the translation included in the update coming on Monday

2021-06-28 04:16 UTC, dpaulino approved these changes
Thanks!

2021-06-28 05:05 UTC, merged