Fixed czech translation of settings dialog
jenius-apps/ambie pull request #82
Opened 2020-12-08 17:25 UTC by MichalMoudry

Fixed czech translation of the settings dialog based on an issue.

2020-12-08 18:21 UTC, dpaulino requested changes

2020-12-08 18:21 UTC, dpaulino commented on src/AmbientSounds.Uwp/Strings/cs-CZ/Resources.resw
> +    <value>Světlý</value>
@MichalMoudry thank you again for your help with this! We've changed how translations work. You no longer have to edit the .resw file. Instead, we'll be editing the .xlf file. All edits made in the .xlf will be automatically added into the .resw when you compile the app. This new system is more flexible than editing the .resw files directly. Please try reverting these changes > then applying the translation fix in the appropriate .xlf. More details here: https://github.com/jenius-apps/ambie#improving-an-existing-language-can-be-done-with-any-text-editor

2020-12-09 11:54 UTC, MichalMoudry commented
It should be fine, unless I should have kept the changes to .resw files after compiling app.

2020-12-09 22:11 UTC, dpaulino approved these changes
Looks good, thanks!

2020-12-09 22:11 UTC, merged